- id: '1693426181583'
  alias: Bath_button
  description: Переключение света кнопкой на столешнице в ванной
  trigger:
  - device_id: 6f8faada9a52be034b8e9981c002be8f
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 85cfb55d171004cf7d70a375c49409e6
    entity_id: b51c26ddbd2a570d5c97879e4036a140
    domain: light
  mode: single
- id: '1693601083173'
  alias: Kori_All_Off
  description: Выключение света кнопкой из прихожей
  trigger:
  - device_id: f801ad359d38df377697684f2ddb3e25
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button
  condition: []
  action:
  - service: script.light_and_vent_off
    data: {}
  mode: single
- id: '1693664638087'
  alias: Prih_Auto_On
  description: Включение света в прихожей по ПИР сенсору
  trigger:
  - type: motion
    platform: device
    device_id: 8c57eecb33ee8eb753b8acebe6e35867
    entity_id: 58814817d7583a63b52fa36eebdd3fb3
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 54cf6a9b25e7119d17a46e0ebab47c97
    entity_id: 2b442183a80875d001c645aa241b43e9
    domain: light
    flash: short
  mode: single
- id: '1693664730231'
  alias: Prih_Auto_Off
  description: Выключение света в прихожей при отсутствии движения в течении 5 минут
  trigger:
  - type: no_motion
    platform: device
    device_id: 8c57eecb33ee8eb753b8acebe6e35867
    entity_id: 58814817d7583a63b52fa36eebdd3fb3
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: 54cf6a9b25e7119d17a46e0ebab47c97
    entity_id: 2b442183a80875d001c645aa241b43e9
    domain: light
  mode: single
- alias: Notify about HA start
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.al_telegram
    data:
      message: Home Assistant - started
  id: 50ea89a2c3a34f16ab9017e17ba76e72
- id: '1696366493855'
  alias: Low battery level detection and notification
  description: ''
  use_blueprint:
    path: BatteryNotifier.yaml
    input:
      actions:
      - service: notify.al_telegram
        data:
          message: 'Low level detected for:

            {{sensors}}'
      threshold: 10
      time: '18:12:00'
- id: '1698001481300'
  alias: Timered_Leak_Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - timer.notification_timer
    from: active
    to: idle
  - platform: state
    entity_id:
    - binary_sensor.leak_sensor_1_moisture
    - binary_sensor.lumi_lumi_sensor_wleak_aq1_moisture
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.leakprotection_switch
    to:
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.leak_sensor_1_moisture
      state: 'on'
    - condition: state
      entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_moisture
      state: 'on'
  action:
  - service: notify.al_telegram
    data:
      message: Обнаружена протечка!!!
  - service: notify.ni_telegram
    data:
      message: Обнаружена протечка, срочно домой!
  - if:
    - condition: state
      entity_id: input_boolean.leakprotection_switch
      state: 'on'
    then:
    - service: timer.start
      data: {}
      target:
        entity_id: timer.notification_timer
  - service: timer.start
    data: {}
    target:
      entity_id: timer.notification_timer
    enabled: false
  mode: single
- id: '1707253277250'
  alias: Alice_kitchenLightOn
  description: ''
  trigger:
  - platform: event
    event_type: yandex_scenario
    event_data:
      scenario_name: KitchenLightOn
  condition: []
  action:
  - type: turn_on
    device_id: 33accf107bcc4993a57d30c782990d5d
    entity_id: e73dbeae875988e660fbe4ed3c198ee3
    domain: light
  mode: single
- id: '1707253767746'
  alias: Alice_tableLightOn
  description: ''
  trigger:
  - platform: event
    event_type: yandex_scenario
    event_data:
      scenario_name: TableLightOn
  condition: []
  action:
  - type: turn_on
    device_id: 389a819c9ae2d1a40585648688eed7a5
    entity_id: 8801a601e10ee26d3381cd9281d9df4f
    domain: light
  mode: single
- id: '1707254667769'
  alias: Alice_tableLightOff
  description: ''
  trigger:
  - platform: event
    event_type: yandex_scenario
    event_data:
      scenario_name: TableLightOff
  condition: []
  action:
  - type: turn_off
    device_id: 389a819c9ae2d1a40585648688eed7a5
    entity_id: 8801a601e10ee26d3381cd9281d9df4f
    domain: light
  mode: single
- id: '1707254742481'
  alias: Alice_kitchenLightOff
  description: ''
  trigger:
  - platform: event
    event_type: yandex_scenario
    event_data:
      scenario_name: KitchenLightOff
  condition: []
  action:
  - type: turn_off
    device_id: 33accf107bcc4993a57d30c782990d5d
    entity_id: e73dbeae875988e660fbe4ed3c198ee3
    domain: light
  mode: single
- id: '1707255646833'
  alias: Alice_allOff
  description: ''
  trigger:
  - platform: event
    event_type: yandex_scenario
    event_data:
      scenario_name: AllOff
  condition: []
  action:
  - type: turn_off
    device_id: 33accf107bcc4993a57d30c782990d5d
    entity_id: e73dbeae875988e660fbe4ed3c198ee3
    domain: light
  - type: turn_off
    device_id: 389a819c9ae2d1a40585648688eed7a5
    entity_id: 8801a601e10ee26d3381cd9281d9df4f
    domain: light
  mode: single
- id: '1710279913808'
  alias: Alice_workZoneOff
  description: ''
  trigger:
  - platform: event
    event_type: yandex_scenario
    event_data:
      scenario_name: WorkZoneOff
  condition: []
  action:
  - type: turn_off
    device_id: f2c87943f16eb0a0f69ad37bc3de38e6
    entity_id: 10c25372265ce33ef5b028c24252649e
    domain: light
  mode: single
- id: '1710279959688'
  alias: Alice_workZoneOn
  description: ''
  trigger:
  - platform: event
    event_type: yandex_scenario
    event_data:
      scenario_name: WorkZoneOn
  condition: []
  action:
  - type: turn_on
    device_id: f2c87943f16eb0a0f69ad37bc3de38e6
    entity_id: 10c25372265ce33ef5b028c24252649e
    domain: light
  mode: single
- id: '1710535575458'
  alias: TimeredAlarmAutomation
  description: Это автоматизация будильник
  trigger:
  - platform: time
    at: input_datetime.alarmtime
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.coverautoopen
      state: 'on'
    then:
    - device_id: 881d332feeff986baf8ea051c82e34f9
      domain: cover
      entity_id: ad362e208a23ff5e3eda9750b90e7553
      type: open
  - if:
    - condition: state
      entity_id: input_boolean.morningwithalice
      state: 'on'
    then:
    - service: script.alicerun
      data: {}
  mode: single
