# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Telegram notifier
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    parse_mode: html
    allowed_chat_ids:
      - 1741664058
      - 226095421

notify:
  - name: al_telegram
    platform: telegram
    chat_id: 1741664058

  - name: ni_telegram
    platform: telegram
    chat_id: 226095421

mqtt:
  sensor:
    - name: "MQTT Temperature Sensor"
      state_topic: "sensor/temperature"
      unit_of_measurement: "c"
      device_class: "temperature"

# custom ZHA quirks folder
zha:
  custom_quirks_path: /config/custom_zha_quirks/

openhasp:
  plate35:
    objects: !include_dir_merge_list openhasp_pages/
