esphome:
  name: 123
  friendly_name: 123

esp32:
  board: esp32s3box
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oUETTNQKefQ0ooie+fpNE4zFG48AOhsO7+zR6A3GvKA="

ota:
  password: "d834843ec50c7f94113d9c61a5b7a7f8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "123 Fallback Hotspot"
    password: "wECISujfHbkz"

captive_portal:
    