esphome:
  name: esphome-web-0f7a2c
  friendly_name: ESPHome Web 0f7a2c

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "W8fJ+MjX9p01gYlk5WpQAqIeZ1pd23S8rWePBGSYf0M="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-0F7A2C"
    password: "U5qzhxCKTXb4"

captive_portal:
    
switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin: 5