esphome:
  name: testesphome
  friendly_name: PWM_t1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ii02OXuykCspaYqW8gFXe+9LzmUOS4yNURDJDjdk3GQ="

ota:


wifi:
  ssid: "TP-Link_3D42"
  password: "40767833"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-C7Cd48"
    password: "U36Ys4qQKGhE"

captive_portal:
    

switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin: 5